### ISSUE TITLE
Failed to retrieve notifier configuration

### ISSUE THREAD

**Issue by ronilaukkarinen** [Tautulli/Tautulli-Issues#105]
**Version:** 2.1.18
**Branch:** master
**Commit hash:** a8a676b79496b4dc3dea9596dfd09a4eeeae60e0
**Operating system:** Linux 4.13.16-100.fc25.x86_64 (#1 SMP Mon Nov 27 19:52:46 UTC 2017 - Fedora 25 Twenty Five)
**Python version:** 2.7.13 (default, Dec 1 2017, 09:21:53) [GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]
**What you did?** Tried to install notification agent (Script), edited it and changed path of script
**What happened?** Error "Failed to retrieve notifier configuration. Check the logs for more info.". Can't remove or edit notification agent.
**What you expected?** Edit/remove the notification agent.

**How can we reproduce your issue?**
Add notification agent Script, path as /usr/bin, then change to home path. (both dirs have lots of scripts)

**Link to logs:**
https://rolle.design/tautulli.log

**Comment by Arcanemagus** [comment]
Can you shut down Tautulli, open your `tautulli.db` in [DB Browser for SQLite](http://sqlitebrowser.org/) and run this?
```sql
DROP TABLE notifiers;
```

Note that you will need to re-create any existing Notification Agents.

If you run into issues with that please hop into the #support channel in the [Discord server](https://tautulli.com/discord).

----

If you are able to trigger this error reliably, please provide steps to do so so this can be fixed, otherwise this looks to be a fluke occurrence.

**Comment by ronilaukkarinen** [comment]
Yeah, everything works now, thanks for the tip (I'm new to SQLite)! Strange bug. To be exact, I changed **Script folder** accidentally to **/home/rolle** (which has thousands of files). Maybe too long file list and no check, could that be the reason?
