### ISSUE TITLE
V2.1.20 Libraries/History/Users tab stuck fetching rows.

### ISSUE THREAD

**Issue by whtdrgn** [Tautulli/Tautulli-Issues#118]
Git Branch: | master
Git Commit Hash: | 4944ce1ca05af75efd8ad5df30cf537ae43bace0
Platform: | Windows 10 (10.0.17134)
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

Was working before this mornings update to version 2.1.20.  It would appear that running it locally from the server everything is working just fine but when I try and access from another system all I get is fetching rows.

I have already cleared my cache and tried additional systems along with different browsers all with the same response.

**Comment by samwiseg00** [comment]
Issues aren't the place for support, please use one of the [available options](https://tautulli.com/#support), with the [Discord server](https://tautulli.com/discord) being preferred.

Before heading there though, this is almost certainly due to your out of date version of Python not understanding how to connect properly.
