### ISSUE TITLE
Tautulli showing old movie title

### ISSUE THREAD

**Issue by PuppyLover101** [Tautulli/Tautulli-Issues#250]
**Describe the Bug**
Tautulli is showing the old title of movie/tv show in the watch statistics page.

**Steps to Reproduce**
1. Watch a movie/tv show
2. Movie/TV Show gets saved to watch statistics
3. Change the movie/tv show manually or by changing agents
4. View statistics and it will show old title

**Expected Behavior**
Movie/TV Show title matches the plex database

**Screenshots**
Tautulli Screenshot: https://i.imgur.com/gt4x3Wz.png
Plex Screenshot: https://i.imgur.com/pl7FY25.png

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.44
- Git Branch: master
- Git Commit Hash: 7f178e091349a1399395c1ac3227d6f0fa801efc
- Platform and Version: Windows 10 LTSC
- Python Version: 2.7.18
- Browser and Version: Chrome 83

**Link to logs (required)**
https://gist.githubusercontent.com/PuppyLover101/4bec0515dcd213438e63200858242921/raw/6d33db081e55c789d429da31e9717a484ad9a8df/log

**Comment by JonnyWong16** [comment]
That's not a bug. That is how it is supposed to behave since that was the title at the point in time you watched the movie. Changing metadata in Plex will never change historical data in Tautulli.

Please refer to the FAQ:
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#move-media

**Comment by PuppyLover101** [comment]
Solved. Thanks @JonnyWong16
