### ISSUE TITLE
Removal of "Monitor Plex Remote Access" feature

### ISSUE THREAD

**Issue by drzoidberg33** [Tautulli/Tautulli-Issues#251]
This feature calls a plex.tv service which asks it to make a request to the PMS instance to see if it's reachable and update its records. This is a relative expensive operation to run and can also be rate limited (especially when it's being called so frequently by Tautulli) causing issues in the Plex Web client where it can't determine the online state.

This endpoint will be restricted in a future release of PMS which will cause this functionality to no longer work in Tautulli so it's recommended that this be removed or replaced with something that doesn't call the plex.tv service.

**Comment by JonnyWong16** [comment]
I don't want to completely remove the feature but instead agree to a method to determine the remote access state that will work with Plex.

I'm assuming that the API call in question is `PUT http://localhost:32400/myplex/refreshReachability` which triggers a check using  Plex.tv services.

The other API call `GET http://localhost:32400/myplex/account` that is used to get the mapping state for remote access should not affect Plex.tv.

How often does the PMS perform it's remote access check? I can remove the `/myplex/refreshReachability` call, but can we rely on the PMS to correctly update the remote access status (at it's own interval) so that Tautulli can get the correct mapping state from `/myplex/account`? 

The other possibility is to use the `reachability` websocket event, then check  `/myplex/account` for the detailed info when this even is received. Again, how often does PMS perform this check? This would be my preferred option so the PMS can notify Tautulli when there are remote access issues instead of pinging the server.
```
{"NotificationContainer":{"type":"reachability","size":1,"ReachabilityNotification":[{"reachability":true}]}}
```

**Comment by JonnyWong16** [comment]
@drzoidberg33 Any answers to my questions above?

**Comment by drzoidberg33** [comment]
Sorry for the delay.

> The other API call GET http://localhost:32400/myplex/account that is used to get the mapping state for remote access should not affect Plex.tv.

Correct, and this data should always be up-to-date.

> How often does the PMS perform it's remote access check? 

Generally only when it needs to, e.g. when there are account changes, network changes, etc. so the `/myplex/account` data you get back should always reflect the most recent values for this.

> The other possibility is to use the reachability websocket event, then check /myplex/account for the detailed info when this event is received. Again, how often does PMS perform this check?

That's definitely a valid route to take. As mentioned there is no fixed interval that PMS does this check (although we do at minimum check every 24 hours) - it could end up getting triggered many times in one hour or not all for multiple hours, it just depends on the conditions.

**Comment by JonnyWong16** [comment]
Thanks for the info.

**Comment by clowg** [comment]
Where has the setting to disable this remote access check gone?  
My PMS thinks that remote access is down/up every few minutes, even though it isn't, so I don't to receive notifications from Tautulli every time this happens.

**Comment by JonnyWong16** [comment]
There is no setting to enable/disable monitoring remote access. It is automatically enabled now as long as the websocket to your Plex server is connected.

As mentioned above the Plex server only performs this check at its own interval. The notification is entirely dependent on the Plex server telling Tautulli through the websocket events if remote access is down. Tautulli no longer performs this check. If the Plex server fails to tell Tautulli that its remote access is down, then unfortunately there is no way for Tautulli to know about it and send a notification.

**Comment by clowg** [comment]
Thanks Jonny.  I understand the changes you have made, but the issue is that PMS has a open issue whereby it repeatedly thinks Remote Access is down.  The issue Tautulli creates for me is it sends an email every time PMS RA supposedly goes up & down.  See attachment.

![image](https://user-images.githubusercontent.com/20178585/89115085-f7487700-d4d7-11ea-84c8-8bf0e4dc4b1b.png)

I've tried working with Plex on this issue, but they still haven't solved it.  As far as my remote users are concerned, RA is not down when PMS reports it is.

Can u see why it is nice to be able to prevent Tautulli from sending these emails?

Geoff.

**Comment by JonnyWong16** [comment]
If it's bothering you then you can disable the notification trigger in your notification agent.

**Comment by agrider** [comment]
I am also receiving these same notifications constantly since updating. I can't tell from the conversation, is the issue with the Tautulli change to websockets or something on Plex's end? It's super annoying but I'm not willing to shut off the capability to tell when access is down entirely, as obviously that is a useful feature. Assuming the issue isn't on Tautulli's end, in which case it should be fixed, would it be possible to adjust the temporal sensitivity of the notification so that we can say "only notify me if plex is unavailable for X minutes" or something?

**Comment by TheMeanCanEHdian** [comment]
Plex sends a websocket event when it checks and says the connection is down. There is no longer any Tautulli logic in the mix. It's the same as any play, stop, or pause event.

**Comment by agrider** [comment]
Presumably, though, Tautulli receives those events to process them and fire the notifications right? Could a buffer not be implemented to hold "Unavailable" events and only pop notifications if a corresponding "Available" event isn't received within a user-specified time period? This would allow users to still receive push notifications if their server is unavailable on a basis that they feel is important without literally spamming the crap out of them?

**Comment by clowg** [comment]
I like your idea @agrider.  It would be a good improvement.

**Comment by clowg** [comment]
I have worked with Plex support a few months ago to try and solve this remote access detection bug, but they have been unable to stamp it out.  I'll have to have another go at them when I get time.

**Comment by TheMeanCanEHdian** [comment]
Any additional logic like that should go in as a feature request on [FeatHub](https://feathub.com/Tautulli/Tautulli).

Plex does not reliably check this status at any set rate which would complicate your idea as seen in the response from Plex above.

>How often does the PMS perform it's remote access check?
Generally only when it needs to, e.g. when there are account changes, network changes, etc. so the /myplex/account data you get back should always reflect the most recent values for this.

**Comment by agrider** [comment]
I don't think Plex's rate really matters since Tautulli is simply listening for events anyway. You just start a timer when you receive the unavailable event and if the timer expires before receiving a corresponding available event, you fire a notification. If you do get an available notification before the timer expires, you clear the timer and discard the events. Then make the timer duration user configurable with a reasonable default. 

Anyway, I've opened a feature request on FeatHub, thanks.
