### ISSUE TITLE
Docker ignores setting of Plex Logs Folder via Environment - Manual setup needed.

### ISSUE THREAD

**Issue by GAS85** [Tautulli/Tautulli-Issues#257]
**Describe the Bug**
When Docker container is up and running as per documentation it is required to mount Plex Logs folder to the `/plex_logs` of container. BUT this folder is not configured in a Tautulli and should be manually added after Setup is finished.
```
grep pms_logs_folder tautulli/config/config.ini
pms_logs_folder = ""
```
It is hard to find this option, because it is in advanced section. After added correct path via UI config.ini will be updated:
```
grep pms_logs_folder tautulli/config/config.ini
pms_logs_folder = /plex_logs
```

**Steps to Reproduce**
1. Deploy docker container as described in a https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#docker
2. Go to GUI and finish installation of Application
3. On a left side open Logs and see that no Plex logs are provided
4. Go to settings and set correct Plex Logs in advanced section.

**Expected Behavior**
It should be ensured ether via Docker Variables, or per default `config.ini` in container that Plex Logs folder is mapped in `plex_logs`

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.1.29]
- Git Branch: master
- Git Commit Hash: 7f178e091349a1399395c1ac3227d6f0fa801efc
- Platform and Version: Docker Linux
- Python Version: 2.7.17
- Browser and Version: Firefox 77.0.1

**Comment by TheMeanCanEHdian** [comment]
Plex logs are not required, however, if you configure it as the wiki instructs all you need to do is adjust the UI setting for the Logs folder (Show advanced, Plex Media Server -> Logs Folder) to be /plex_logs. The <path to plex logs> needs to be replaced with the physical location of the plex logs folder on your machine outside the container.

You should not have to make any changes to the config.ini directly.

**Comment by JonnyWong16** [comment]
The setting must be entered manually on the settings page because the mounted folder could be anything and not necessarily `/plex_logs`. For example, the [linuxserver/tautulli](https://hub.docker.com/r/linuxserver/tautulli) container uses `/logs`. Or the user could change the mount path to anything they want. It's a folder mount, not an environment variables, so there is no way to automatically determine what the path is, or if it has even been mounted. It is an advanced setting because Plex logs are not required and competely optional to use Tautulli as a log viewer. 

I have already planned to remove the Plex logs from the installation instructions with the next update. The log viewer will still be in Tautulli, but it will be entirely up to the user to mount the folder wherever they want if they want to use that feature.

**Comment by GAS85** [comment]
Thats fine for me if it works well without access to the logs, should we have a hint somewhere in wiki that if user still want to see logs via standard webUI he should give an access to them, e.g. via mount it to the container?
Or what is the purpose of this feature? I thought Tautulli fetched some information from the plex logs also, but looks it is not the case.

**Comment by JonnyWong16** [comment]
As I mentioned above, Tautulli can be used as a log viewer. The wiki page and Docker instructions have already been update.

Closing this issue.
