### ISSUE TITLE
Live TV library is not being recreated after server identifier is changed

### ISSUE THREAD

**Issue by gogorichie** [Tautulli/Tautulli-Issues#261]
**Describe the Bug**
After importing multiple TAUTULLI database files into version 2.5 I ended up with duplicate libraries. I visited the http://localhost:8181/delete_duplicate_libraries URL and removed the duplicates. I noticed it removes the Live TV library as well causing the graphs tab to not display Live TV. The Live TV details in the History tab display correctly.

**Steps to Reproduce**
1.	Verify live TV Library is present in the Libraries tab 
2.	Confirm live TV data is displayed on the Graph tab
3.	Import a TAUTULLI db file
4.	Visit http://localhost:8181/delete_duplicate_libraries _replacing localhost with the appropriate path_ 
5.	Go back to the libraries tab and notice live TV library is missing
6.	Go to the Graphs tab notice the live TV data is missing 

**Expected Behavior**
When removing duplicate libraries the live TV library is not removed.

**Screenshots**
![image](https://i.imgur.com/aF5zYuC.png)
![image](https://i.imgur.com/oaRMJAo.png)
![image](https://user-images.githubusercontent.com/29635364/86850144-6a480480-c076-11ea-9a02-7dc7f7444172.png)

**Tautulli and System Info**
- Version: V2.5.2
- Git Branch: master
- Git Commit Hash: 356f64cac0e41fc29c542be298aa6eac25a369f0
- Platform and Version: 	[Docker] Linux 4.19.107-Unraid (#1 SMP Thu Mar 5 13:55:57 PST 2020 - Debian GNU/Linux 10 buster)
- Python Version: 3.8.3 (default, Jun 9 2020, 17:49:41) [GCC 8.3.0]
- Browser and Version: [e.g. Chrome 74]

**Link to logs**
[Tautulli Logs](https://gist.github.com/gogorichie/ab64bef4c16f6d660e7be45e0d144db3).

**Comment by JonnyWong16** [comment]
So this is actually the correct behaviour of `/delete_duplicate_libraries`. The Live TV library should be removed when your server identifier is changed because it is no longer associated with the same server.

The problem is a new Live TV library is not automatically created the *next time live TV is played* (I will fix this). It *should not* be created because you have Live TV in your history. If it doesn't show up the next time live TV is played (after I fix it), then it should be able to [undelete the library](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q12) with `/undelete_library?section_name=Live TV`.
