### ISSUE TITLE
Purging duplicated "Library not on plex server" resulted in purging data from other libraries as well

### ISSUE THREAD

**Issue by jancoow** [Tautulli/Tautulli-Issues#281]
Hi.

For some reason, all my libraries were duplicated a while back. While it has the same "last played" and same "total plays", it didn't had the same number of movies/seasons. In the newest release, a triangle appeared with "library not on Plex server", so I was like, okay let's delete it then. I pressed purge on my movies library, and guess what. It also purged all the play history from the valid movie library! And to make it worse, the library is still not removed. 
So a few questions regarding to this:

- How can I get the play data back.
- Why does it show duplicate library, which is not really a duplicate apparently because it shares the same watch history? 
- How can I fix this?

![image](https://user-images.githubusercontent.com/9000749/95021435-3e3a2080-0671-11eb-87f6-84f42da62ac6.png)

Here a screenshot to show you the triangle.

**Comment by JonnyWong16** [comment]
1. Do not erase the template when creating a GitHub issue. Fill out all the info in the template.
2. Restore a back up of your database and read the FAQ.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q8

**Comment by jancoow** [comment]
Ah, I didn't know it was there. That was my bad. Seems to work fine, where are the backups stored?

**Comment by JonnyWong16** [comment]
In your backups folder which is listed on the main settings page.

**Comment by Arcanemagus** [comment]
> Tho that doesn't solve that the purge button is not removing the library :)

That's because the Purge button is there to purge the history... not delete the library. If it was meant to delete it then it would be a Delete button 😉.

The FAQ entry covers how to remove duplicate libraries, if you ever need to fully delete a library you need to do that from Edit Mode in the Libraries list... again, don't try to delete duplicate libraries like that though.

If you need further help please use one of the [support options](https://tautulli.com/#support), with [Discord](https://tautulli.com/discord) being preferred.
